services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    GollumSF\EmailBundle\Builder\EmailBuilderInterface:
        class: GollumSF\EmailBundle\Builder\EmailBuilder

    GollumSF\EmailBundle\Sender\EmailSenderInterface:
        class: GollumSF\EmailBundle\Sender\EmailSender
