language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
  
before_script:
    - composer install --dev

script: phpunit --whitelist=./ --coverage-text --coverage-html=coverage-html

notifications:
    email:
        - smeagolworms4@gmail.com
